name: Build Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js version 20.8.0
      uses: actions/setup-node@v4
      with:
        node-version: version 20.8.0
        cache: 'npm'
    - run: npm install
    - run: npm run test:unit
